name: CI 

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node v18.0.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache CDK Dependencies
        uses: actions/cache@v3
        id: cache_cdk_dependency_id
        env:
          cache-name: cache-cdk-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        # if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: Format
        run: yarn format:dev
      
      - name: Lint
        run: yarn lint:dev
      
      - name: Update Token
        run: yarn test authorize
      
      - name: Test
        run: yarn test
      
      - name: Build
        run: yarn build
